import { createActions } from "reduxsauce";

const { Types, Creators } = createActions({
  changeDistributorForm: ["payload"],

  submitSelectedDistributorForm: ["payload"],
  submitSelectedDistributorFormSuccess: ["payload"],
  submitSelectedDistributorFormFailure: null,
  submitSelectedDistributorFormLoading: null,
  submitSelectedDistributorFormLoadingStop: null,

  updateDistributorForm: ["payload"],
  changeDistributorSearchFilters: ["payload"],

  submitEditedDistributorForm: ["payload"],
  submitEditedDistributorFormSuccess: ["payload"],
  submitEditedDistributorFormFailure: null,
  submitEditedDistributorFormLoading: null,
  submitEditedDistributorFormLoadingStop: null,

  getDistributor: ["payload"],
  getDistributorSuccess: ["payload"],
  getDistributorFailure: ["payload"],
  getDistributorLoading: null,
  getDistributorLoadingStop: null,

  getAllArea: ["payload"],
  getAllAreaSuccess: ["payload"],
  getAllAreaFailure: ["payload"],
  getAllAreaLoading: null,
  getAllAreaLoadingStop: null,
  getResidenceArea: ["payload"],
  getResidenceAreaSuccess: ["payload"],
  getResidenceAreaFailure: ["payload"],
  getResidenceAreaLoading: null,
  getResidenceAreaLoadingStop: null,

  getAllPincode: ["payload"],
  getAllPincodeSuccess: ["payload"],
  getAllPincodeFailure: ["payload"],
  getAllPincodeLoading: null,
  getAllPincodeLoadingStop: null,
  getResidencePincode: ["payload"],
  getResidencePincodeSuccess: ["payload"],
  getResidencePincodeFailure: ["payload"],
  getResidencePincodeLoading: null,
  getResidencePincodeLoadingStop: null,

  getAllState: ["payload"],
  getAllStateSuccess: ["payload"],
  getAllStateFailure: ["payload"],
  getAllStateLoading: null,
  getAllStateLoadingStop: null,
  getResidenceState: ["payload"],
  getResidenceStateSuccess: ["payload"],
  getResidenceStateFailure: ["payload"],
  getResidenceStateLoading: null,
  getResidenceStateLoadingStop: null,

  getAllSubState: ["payload"],
  getAllSubStateSuccess: ["payload"],
  getAllSubStateFailure: ["payload"],
  getAllSubStateLoading: null,
  getAllSubStateLoadingStop: null,
  getResidenceSubState: ["payload"],
  getResidenceSubStateSuccess: ["payload"],
  getResidenceSubStateFailure: ["payload"],
  getResidenceSubStateLoading: null,
  getResidenceSubStateLoadingStop: null,

  getAllZone: ["payload"],
  getAllZoneSuccess: ["payload"],
  getAllZoneFailure: ["payload"],
  getAllZoneLoading: null,
  getAllZoneLoadingStop: null,
  getResidenceZone: ["payload"],
  getResidenceZoneSuccess: ["payload"],
  getResidenceZoneFailure: ["payload"],
  getResidenceZoneLoading: null,
  getResidenceZoneLoadingStop: null,

  getAllDistrict: ["payload"],
  getAllDistrictSuccess: ["payload"],
  getAllDistrictFailure: ["payload"],
  getAllDistrictLoading: null,
  getAllDistrictLoadingStop: null,
  getResidenceDistrict: ["payload"],
  getResidenceDistrictSuccess: ["payload"],
  getResidenceDistrictFailure: ["payload"],
  getResidenceDistrictLoading: null,
  getResidenceDistrictLoadingStop: null,

  getAllCity: ["payload"],
  getAllCitySuccess: ["payload"],
  getAllCityFailure: ["payload"],
  getAllCityLoading: null,
  getAllCityLoadingStop: null,
  getResidenceCity: ["payload"],
  getResidenceCitySuccess: ["payload"],
  getResidenceCityFailure: ["payload"],
  getResidenceCityLoading: null,
  getResidenceCityLoadingStop: null,

  distributorFormValidationFailed: ["payload"],

  selectDistributor: ["payload"],
  selectDistributorSuccess: ["payload"],

  extractFormData: ["payload"],

  updateDistributor: ["payload"],
  updateDistributorLoading: null,
  updateDistributorSuccess: ["payload"],
  updateDistributorFailure: null,
  updateDistributorLoadingStop: null,

  clearDistributorForm: null,

  sendApproval: ["payload"],
  sendApprovalSuccess: ["payload"],
  sendApprovalFailure: null,
  sendApprovalLoading: null,
  sendApprovalLoadingStop: null,

  submitDistributorFormValidationFailed: ["payload"],

  addStockForm: ["payload"],
  removeStockForm: ["payload"],
  addCustomerForm: ["payload"],
  removeCustomerForm: ["payload"],
  addFirmForm: ["payload"],
  removeFirmForm: ["payload"],
  getSubCategory: ["payload"],
  getSubCategorySuccess: ["payload"],
  getSubCategoryFailure: ["payload"],
  getSubCategoryLoading: null,
  getSubCategoryLoadingStop: null,
  changeStockForm: ["payload"],
  changeCustomerForm: ["payload"],
  changeFirmForm: ["payload"],
  changeUpdateStockForm: ["payload"],
  changeUpdateCustomerForm: ["payload"],
  changeUpdateFirmForm: ["payload"],
  clearUpdateLongForm: null,
  doNothing: null,

  addCustomerSale: ["payload"],
  bestCustomer: ["payload"],
  firstYearSale: ["payload"],
  clearTerritory: null
});

export const DistributorTypes = Types;
export default Creators;
