import { createActions } from "reduxsauce";

const { Types, Creators } = createActions({
  changeDashboardSearchFilters: ["payload"],
  clearSearchFilter:null,
  changeDashboardOrderFilters: ["payload"],
  resetFilter:null,
  getOrderValue: ["payload"],
  getVisitCount: ["payload"],
  getSiteCount: ["payload"],
  getCounters: ["payload"],
  getEventCount: ["payload"],
  getDashboardSummary: ["payload"],
  getDashboardBanner: ["payload"],
  getTicker: ["payload"],
  getPrimarySummary: ["payload"],
  getSecondarySummary: ["payload"],
  getAllBrands: ["payload"],
  getAllClass: ["payload"],
  getCity: ["payload"],
  getArea: ["payload"],
  getZone: ["payload"],
  getState: ["payload"],
  getSubState: ["payload"],
  getDistrict: ["payload"],
  dashboardOrderFilter: ["payload"],
  getDrs: ["payload"],

  getOrderValueSuccess: ["payload"],
  getVisitCountSuccess: ["payload"],
  getSiteCountSuccess: ["payload"],
  getCountersSuccess: ["payload"],
  getEventCountSuccess: ["payload"],
  getDashboardSummarySuccess: ["payload"],
  getDashboardBannerSuccess: ["payload"],
  getTickerSuccess: ["payload"],
  getPrimarySummarySuccess: ["payload"],
  getSecondarySummarySuccess: ["payload"],
  getAllBrandsSuccess: ["payload"],
  getAllClassSuccess: ["payload"],
  getCitySuccess: ["payload"],
  getAreaSuccess: ["payload"],
  getZoneSuccess: ["payload"],
  getStateSuccess: ["payload"],
  getSubStateSuccess: ["payload"],
  getDistrictSuccess: ["payload"],
  dashboardOrderFilterSuccess: ["payload"],
  getDrsSuccess: ["payload"],


  getOrderValueFailure: null,
  getVisitCountFailure: null,
  getSiteCountFailure: null,
  getCountersFailure: null,
  getEventCountFailure: null,
  getDashboardSummaryFailure: null,
  getDashboardBannerFailure: null,
  getTickerFailure: null,
  getPrimarySummaryFailure: null,
  getSecondarySummaryFailure: null,
  getAllBrandsFailure: null,
  getAllClassFailure: null,
  getCityFailure: null,
  getAreaFailure: null,
  getZoneFailure: null,
  getStateFailure: null,
  getSubStateFailure: null,
  getDistrictFailure: null,
  dashboardOrderFilterFailure: null,
  getDrsFailure: null,


  getOrderValueLoading: null,
  getVisitCountLoading: null,
  getSiteCountLoading: null,
  getCountersLoading: null,
  getEventCountLoading: null,
  getDashboardSummaryLoading: null,
  getDashboardBannerLoading: null,
  getTickerLoading: null,
  getPrimarySummaryLoading: null,
  getSecondarySummaryLoading: null,
  getAllBrandsLoading: null,
  getAllClassLoading: null,
  getCityLoading: null,
  getAreaLoading: null,
  getZoneLoading: null,
  getStateLoading: null,
  getSubStateLoading: null,
  getDistrictLoading: null,
  dashboardOrderFilterLoading: null,
  getDrsLoading: null,

  getOrderValueLoadingStop: null,
  getVisitCountLoadingStop: null,
  getSiteCountLoadingStop: null,
  getCountersLoadingStop: null,
  getEventCountLoadingStop: null,
  getDashboardSummaryLoadingStop: null,
  getDashboardBannerLoadingStop: null,
  getTickerLoadingStop: null,
  getPrimarySummaryLoadingStop: null,
  getSecondarySummaryLoadingStop: null,
  getAllBrandsLoadingStop: null,
  getAllClassLoadingStop: null,
  getCityLoadingStop: null,
  getAreaLoadingStop: null,
  getZoneLoadingStop: null,
  getStateLoadingStop: null,
  getSubStateLoadingStop: null,
  getDistrictLoadingStop: null,
  dashboardOrderFilterLoadingStop: null,
  getDrsLoadingStop: null,


  dashboardFilter: ["payload"],
  doNothing: null,
});

export const DashboardTypes = Types;
export default Creators;
