import { HelperService } from "App/Services/Utils/HelperService";

export const INITIAL_STATE = {
  searchFilters: {
    startDate: HelperService.getMonthStartAndEndDateTimestamp()[0],
    endDate: HelperService.getMonthStartAndEndDateTimestamp()[1],
    selectedDateType: "Date", //or Month,
    selectedMonth: new Date(HelperService.getCurrentTimestamp()).getMonth(),
    selectedTab: 0,
    psm__c: "",
    selectedTabRetail: 0,
    selectedTabonboard:0
  },
  tabsMapping: {
    "0": "Targets Achieved",
    "1": "Summary",
  },
  filter: [],
  searchDashboardOrderFilters: {
    brand: [],
    itemClass: [],
    zone: [],
    state: [],
    sub: [],
    district: [],
    city: [],
    area: [],
  },

  data: {
    siteCount: {},
    visitCount: {},
    eventsCount: {},
    orderValue: {},
    counters: {},
    dashboardSummary: {},
    dashboardBanner: {},
    ticker: {},
    primarySummary: {},
    secondarySummary: {},
    brand: {},
    itemClass: {},
    city: {},
    state: {},
    subState: {},
    zone: {},
    district: {},
    area: {},
    filterOrder: {},
    drsValue: {},
  },
  loaders: {
    siteCountLoader: false,
    visitCountLoader: false,
    eventsCountLoader: false,
    orderValueLoader: false,
    countersLoader: false,
    dashboardSummaryLoader: false,
    dashboardBannerLoader: false,
    tickerLoader: false,
    primarySummaryLoader: false,
    secondarySummaryLoader: false,
    brandLoader: false,
    itemClassLoader: false,
    cityLoader: false,
    stateLoader: false,
    subStateLoader: false,
    zoneLoader: false,
    districtLoader: false,
    areaLoader: false,
    filterOrderLoader: false,
    drsValueLoader: false,
  },
};
