import { StyleSheet, Dimensions } from "react-native";
import { Colors, Metrics, Helpers, Fonts, ApplicationStyles } from "App/Theme";
import { Row } from "native-base";
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "react-native-responsive-screen";

export default StyleSheet.create({
  mainContainer: {
    // flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingTop: hp("0%"),
  },
  card: {
    flexDirection: "column",
    marginTop: hp("20%"),
    width: wp("100%"),
    // paddingLeft: 3,
    // paddingRight: 3,
    elevation: 10,
    backgroundColor: Colors.background,
    height: hp("20%"),
    justifyContent: "center",
    alignItems: "center",
    // paddingHorizontal: "8%",
    borderBottomLeftRadius: 65,
    borderBottomRightRadius: 65,
  },
  cardBlue: {
    flexDirection: "column",
    marginTop: hp("20%"),
    width: wp("100%"),
    // paddingLeft: 3,
    // paddingRight: 3,
    elevation: 10,
    backgroundColor: Colors.bluebackground,
    height: hp("20%"),
    justifyContent: "center",
    alignItems: "center",
    // paddingHorizontal: "8%",
    borderBottomLeftRadius: 65,
    borderBottomRightRadius: 65,
  },
  titleText: {
    color: Colors.white,
    fontFamily: ApplicationStyles.textFont,
    fontSize: 24,
    fontWeight: "bold",
    // left: "10%",
    bottom: hp("1%"),
    alignSelf:"center"
  },
  textClr: {
    color: Colors.headerClr,
  },
  searchContainer: {
    paddingVertical: 8,
    width: "88%",
    borderRadius: 10,
    paddingHorizontal: 3,
    paddingTop: 0,
    elevation: 10,
    backgroundColor: "white",
    fontSize: wp("4.8%"),
    fontWeight: "700",
    color: Colors.blue,
    height: "25%",
    margin: "2%",

    alignSelf: "center",
  },
  bodyCard: {
    borderRadius: 6,
    elevation: 5,
    backgroundColor: "#fff",
    shadowOffset: { width: 1, height: 1 },
    shadowColor: Colors.darkGreyClr,
    shadowOpacity: 0.3,
    borderColor: Colors.darkGreyClr,
    shadowRadius: 2,
    width: "90%",

    height: "30%",
    alignSelf: "center",
    bottom: "15%",
    flexDirection: "column",

    backgroundColor: Colors.white,
  },

  textStyle: {
    marginLeft: "20%",
    color: Colors.lightGrey,
    fontSize: 14,
    fontWeight: "bold",
    // marginBottom:'15%'
    // alignSelf:'center'
  },
  headerStyle: {
    color: Colors.black,
    fontSize: 20,
    fontWeight: "bold",
    right: "98%",
  },
  textStyle1: {
    marginLeft: "15%",
    color: Colors.lightGrey,
    fontSize: 8,
    padding: 1.5,
    color: Colors.white,
    backgroundColor: Colors.cardblue,
    borderRadius: 8,
    fontFamily: "Segoe UI",
    width: "19%",
    height: "55%",
    textAlign: "center",
    right: wp(19),
    top: hp(1.5),
  },
  cardContent: {
    flexDirection: "column",
    justifyContent: "space-between",
  },
  iconstyle: {
    // left: wp("75%"),
    // top: hp("-4%"),
    marginLeft: wp("1%"),
    marginTop: hp("-1%"),
    // marginBottom:hp("7%"),
    backgroundColor: Colors.phoneClr,
    color: Colors.white,
    borderRadius: 50,
    height: 30,
    width: 30,
    padding: 7,
    fontSize: 18,
  },
  ttl: {
    color: Colors.lightGrey,
    fontSize: wp("3.5%"),
    fontFamily: ApplicationStyles.textFont,
    left: wp("10%"),
    fontWeight: "bold",
    width:wp("30%")
  },
  detail: {
    color: Colors.black,
    fontSize: wp("3.7%"),
    fontFamily: ApplicationStyles.textMsgFont,
    right: wp("5%"),
    fontWeight: "bold",
    width:wp("30%")
  },
  // status: {
  //   color: Colors.white,

  //   fontFamily: ApplicationStyles.textMsgFont,
  //   fontSize: 8,
  //   // marginBottom: 3,
  //   backgroundColor: Colors.cardblue,
  //   width: wp(24),
  //   padding: wp(0.5),
  //   borderRadius:5,
  //   top: hp("1%"),
  //   left: wp("3%"),
  //   height: hp("2%"),
  //   textAlign: "center",
  // },
  backarrow: {
    color: Colors.white,
    fontSize: 32,
    paddingRight: 330,
    paddingTop: 0,
  },
  head: {
    color: Colors.black,
    fontFamily: ApplicationStyles.textMsgFont,
    fontSize: 20,
    textTransform: "capitalize",
    width:wp("30%")
  },
  container: {
    flex: 1,
  },
  plusIcon: {
    borderRadius: 50,
    top: hp("55%"),
    left: wp("35%"),
    borderRadius: 50,
    height: 45,
    width: 45,
    backgroundColor: Colors.button,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 100,
  },
  plusIconBlue: {
    borderRadius: 50,
    top: hp("55%"),
    left: wp("35%"),
    borderRadius: 50,
    height: 45,
    width: 45,
    backgroundColor: Colors.bluebackground,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 100,
  },
});
