export const DummyData = [{
    "amount__c": null,
    "approved_by_head__c": false,
    "approved_by_manager__c": true,
    "arrival_date__c": null,
    "bill_number__c": null,
    "bills__c": null,
    "city__c": null,
    "company_paid__c": false,
    "createddate": 1584274895000,
    "customer__c": "0011m000008SlCoAAK",
    "date__c": 1584230400000,
    "departure_date__c": null,
    "expense__c": "a0s1m0000004ySgAAI",
    "expense_item_approver__c": "a0H1m000001OwvEEAS",
    "expense_status__c": "Draft",
    "expense_type__c": "Local Expense",
    "food__c": null,
    "from__c": "Pratap Vihar, G Block, G Block, Sector-11, Pratap Vihar, Ghaziabad, Uttar Pradesh 201009, India",
    "from_date__c": null,
    "have_bills__c": false,
    "kilometers_travelled__c": 0,
    "mode__c": null,
    "month__c": "Mar",
    "name": "0053",
    "number_of_nights__c": null,
    "outstation_mode__c": null,
    "outstation_type__c": null,
    "pg_id__c": null,
    "place__c": null,
    "remark__c": null,
    "sfid": "a0n1m0000004UyIAAU",
    "team__c": "a0H1m000001Owv4EAC",
    "ticket_number__c": null,
    "to__c": "Chhabil Das Marg, Pocket E, Patel Nagar 2nd, Patel Nagar, Ghaziabad, Uttar Pradesh 201003, India",
    "to_date__c": null,
    "toll_parking_charges__c": null,
    "type__c": null
}]