import { StyleSheet } from "react-native";
import { Colors, Metrics, Helpers, Fonts, ApplicationStyles } from "App/Theme";
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from "react-native-responsive-screen";

export default StyleSheet.create({
  mainContainer: {
    // flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingTop: hp("1.5%"),
  },
  cardstyle: {
    flexDirection: "column",
    paddingTop: hp("2%"),
    paddingBottom: hp("1%"),
    width: wp("100%"),
    paddingLeft: wp("2%"),
    paddingRight: wp("2%"),
    elevation: 10,
    backgroundColor: Colors.background,
    height: hp("23%"),
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: "8%",
    borderBottomLeftRadius: 65,
    borderBottomRightRadius: 65,
  },
  backarrow: {
    color: Colors.white,
    fontSize: 32,
    paddingRight: wp("90%"),
  },
 
  title: {
    color: Colors.white,
    fontFamily: ApplicationStyles.textFont,
    fontSize: 28,
    fontWeight: "bold",
    left: wp("12%"),
    top: hp("-2%"),
  },
  titleText: {
    color: Colors.black,
    fontFamily: ApplicationStyles.textFont,
    fontSize: 28,
    fontWeight: "bold",
  },
  checkicon: {
    left: wp("75%"),
    top: hp("-2.5%"),
    backgroundColor: Colors.phoneClr,
    color: Colors.white,
    borderRadius: 50,
    height: hp(4),
    width: wp(8),
    padding: 5,
    fontSize: 20,
    fontWeight: "bold",
  },
 
  searchContainer: {
    width: wp("50%"),
    borderRadius: 10,
    paddingHorizontal: 3,
    paddingTop: 0,
    elevation: 10,
    backgroundColor: Colors.lightPink,
    fontSize: wp("4.8%"),
    fontWeight: "700",
    color: Colors.blue,
    height: hp("5%"),
    alignSelf: "center",
  },
  status: {
    color: Colors.white,
    fontFamily: ApplicationStyles.textMsgFont,
    fontSize: 10,
    backgroundColor: Colors.cardblue,
    width: wp(15),
    borderRadius: 4,
    top: hp("1%"),
    left: wp("3%"),
    height: hp("2%"),
    textAlign: "center",
  },
  container: {
    flex: 1,
  },
  plusIcon: {
    borderRadius: 50,
    bottom: 75,
    position: "absolute",
    left: 100,
    borderRadius: 50,
    height: 45,
    width: 45,
    backgroundColor: Colors.button,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  date: {
    fontSize: 25,
    fontFamily: "Rubik",
    color: Colors.background,
    left: hp("2%"),
    top: hp("1.5%"),
    fontWeight: "bold",
  },
  month: {
    fontSize: 12,
    fontFamily: "Rubik",
    color: Colors.background,
    left: hp("0%"),
    top: hp("1%"),
    fontWeight: "bold",
  },
  head: {
    fontSize: 18,
    fontFamily: "Rubik",
    left: hp("0%"),
    fontWeight: "bold",
    color: Colors.black,
    width:wp("25%")
  },
  head1: {
    fontSize: 13,
    fontFamily: "Rubik",
    left: hp("-0.4%"),
    top: hp("1.5%"),
  },
  head2: {
    fontSize: 13,
    fontFamily: "Rubik",
    left: hp("-0.4%"),
    top: hp("1.5%"),
    color: Colors.lightGrey,
  },

  ttl: {
    color: Colors.lightGrey,
    fontSize: wp("3%"),
    fontFamily: "Rubik",
    fontWeight: "bold",
    bottom: hp("1%"),
    top: hp("4%"),
    left: wp("-25%"),
  },
  detail: {
    color: Colors.black,
    fontSize: wp("3%"),
    fontFamily: "Rubik",
    fontWeight: "bold",
    bottom: hp("1%"),
    left: wp("-22%"),
    top: hp("4%"),
  },
  ttl1: {
    color: Colors.lightGrey,
    fontSize: wp("3%"),
    fontFamily: "Rubik",
    fontWeight: "bold",
    bottom: hp("1%"),
    top: hp("4%"),
    left: wp("-25%"),
  },
  detail1: {
    color: Colors.black,
    fontSize: wp("3%"),
    width:wp("40%"),
    fontFamily: "Rubik",
    fontWeight: "bold",
    bottom: hp("1%"),
    left: wp("-18%"),
    top: hp("4%"),
  },
  
  placeholder: {
    borderColor: "transparent",
    right: wp("1.5%"),
    fontFamily: "Segoe UI",
    // color:Colors.black,
    fontSize: 13,
    top: hp("2%"),
    fontWeight: "bold",
  },

  outerView: {
    flexDirection: "row",
    flexWrap: "wrap",
    left: "2%",
    right: "5%",
    top: "0%",
    marginBottom: "20%",
  },
  textView: {
    width: wp("38%"),
    borderBottomWidth: 1,
    borderColor: Colors.lightGrey,
    marginTop: hp("1.5%"),
  },

  textView1: {
    width: wp("85%"),
    borderBottomWidth: 1,
    borderColor: Colors.lightGrey,
    marginTop: hp("1.5%"),
  },
  textStyle: {
    fontFamily: "Segoe UI",
    color: Colors.black,
    top: hp("2.5%"),
    fontSize: 13,
    fontWeight: "bold",
  },
  dropDown: {
    width: wp("85%"),
    marginTop: hp("2%"),
    marginBottom:hp("3%")
  },
  dropDownInner: {
    left: wp("5%"),
    top: hp("3.5%"),
  },
  picker: {
    // borderRadius: 100,
    width: wp('85%'),
    // height: hp('5.7%'),
    marginBottom: hp('2%'),
    paddingHorizontal: 8
  },
  button: {
    width: wp("29%"),
    height: hp("5%"),
    top: hp("-5%"),
    left: wp("29%"),
    // paddingBottom: 4,
    borderRadius: 3,
  },
  dropDown1: {
    width: wp("10%"),
    marginTop: hp("1.5%"),
    left: wp("7%"),
    marginBottom: hp("2%"),
  },
  pickerLabel: {
    color: Colors.black,
    flexDirection: "row",
    fontFamily: ApplicationStyles.textFont,
    fontSize: 15,
    padding: 5,
    // textAlign: "left",
    width: "99%",
  },
  picker1: {
    // borderRadius: 10,
    width: wp("30%"),
    marginLeft: 50,
    flex: 1,
    color:"black",
    // height: hp('6%'),
    marginBottom: hp("2%"),
  },
});
